"""KOS Agent: What do I want to learn and improve?"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from kos.graph import KOSKernel
from kos.lexicon import KASMLexicon
from kos.drivers.text import TextDriver
from kos.router_offline import KOSShellOffline
from kos.predictive import PredictiveCodingEngine
from kos.propose import CodeProposer
from kos.self_model import SelfModel
from kos.dreamer import Dreamer, DreamerConfig
from kos.hierarchical import HierarchicalPredictor

kernel = KOSKernel(enable_vsa=False)
lexicon = KASMLexicon()
driver = TextDriver(kernel, lexicon)
pce = PredictiveCodingEngine(kernel, learning_rate=0.05)

driver.ingest("""
Toronto is a major city in the Canadian province of Ontario.
Toronto was founded and incorporated in the year 1834.
The city of Toronto has a population of approximately 2.7 million people.
Toronto has a humid continental climate with warm summers and cold winters.
John Graves Simcoe originally established the settlement of Toronto.
Perovskite is a highly efficient material for photovoltaic cells.
Photovoltaic cells capture photons to produce electricity.
Silicon is a traditional semiconductor for computing.
Backpropagation adjusts weights by computing gradient of the loss.
Artificial neural networks are inspired by biological neurons.
Quantum computers use qubits which can exist in superposition.
Entanglement allows two qubits to be correlated across any distance.
The Sun produces energy through nuclear fusion of hydrogen into helium.
Mitochondria produce ATP which is the energy currency of cells.
Apixaban prevents thrombosis without dietary restrictions.
""")

shell = KOSShellOffline(kernel, lexicon, enable_forager=False)
sm = SelfModel(kernel, lexicon, pce)
sm.sync_beliefs_from_graph()
proposer = CodeProposer(kernel, lexicon, pce)
hp = HierarchicalPredictor(kernel, pce)

# Run dreamer to find gaps
config = DreamerConfig()
config.max_cycles = 10
config.cycle_interval_sec = 0
config.curiosity_probability = 1.0
dreamer = Dreamer(kernel, lexicon, sm, pce, config)

for _ in range(10):
    dreamer.think_once(verbose=False)

# Train hierarchical predictor
benchmark_queries = [
    "Where is Toronto?",
    "When was Toronto founded?",
    "Population of Toronto?",
    "Tell me about perovskite",
    "What is entanglement?",
    "How do neural networks learn?",
    "What produces ATP?",
]

toronto_uid = lexicon.word_to_uuid.get("toronto")
for q in benchmark_queries:
    seeds = []
    import re
    raw = [w.lower() for w in re.findall(r"[a-zA-Z]+", q) if len(w) > 2]
    for w in raw:
        uid = shell._resolve_word(w, list(lexicon.word_to_uuid.keys()))
        if uid:
            seeds.append(uid)
    if seeds:
        hp.predict_full(seeds, q)
        answer = shell.chat(q)
        has_answer = len(answer) > 30 and "don't have" not in answer.lower()
        hp.observe_actual(seeds, {
            "top_energy": 2.0 if has_answer else 0.0,
            "ticks": 8,
            "confidence": 0.9 if has_answer else 0.1,
            "no_answer": not has_answer,
            "foraged": False,
        }, q)

print("=" * 70)
print("  KOS AGENT: What I Want to Learn and Improve")
print("=" * 70)

# ── WHAT I WANT TO LEARN ─────────────────────────────

print("\n[1] WHAT I WANT TO LEARN (Knowledge Gaps)")
print("=" * 60)

# 1a: Concepts I'm uncertain about
uncertain = sm.what_am_i_uncertain_about(0.3)
if uncertain:
    print("\n  [UNCERTAIN BELIEFS] I have %d concepts below 30%% confidence:" % len(uncertain))
    for u in uncertain[:10]:
        print("    - %s (%.0f%% confident)" % (u["concept"], u["confidence"] * 100))
    print("\n  I WANT: Forage Wikipedia for each uncertain concept to strengthen")
    print("  my understanding. Priority: concepts that appear in user queries")
    print("  but where I give weak answers.")

# 1b: Orphan nodes (concepts with no connections)
orphans = [uid for uid, node in kernel.nodes.items()
           if not node.connections]
orphan_words = [lexicon.get_word(uid) for uid in orphans
                if hasattr(lexicon, "get_word")]
orphan_words = [w for w in orphan_words if w]
if orphan_words:
    print("\n  [ORPHAN CONCEPTS] I have %d disconnected concepts:" % len(orphan_words))
    for w in orphan_words[:10]:
        print("    - %s (no connections — isolated knowledge)" % w)
    print("\n  I WANT: Run triadic closure or forage context for each orphan")
    print("  so they become connected to the main knowledge graph.")

# 1c: Curiosity queries generated by dreamer
curiosity_events = [e for e in dreamer.get_events()
                     if "CURIOSITY" in e.get("details", "")]
curiosity_queries = []
for e in dreamer.get_events():
    if e["type"] == "cycle":
        pass  # cycle summaries
unique_curiosities = set()
for e in dreamer.get_events():
    d = e.get("details", "")
    if "Generated:" in d:
        q = d.split("Generated:")[1].strip().strip("'")
        unique_curiosities.add(q)

if unique_curiosities:
    print("\n  [CURIOSITY] My dreamer generated %d self-directed questions:" % len(unique_curiosities))
    for q in list(unique_curiosities)[:10]:
        print("    - %s" % q)
    print("\n  I WANT: Permission to forage answers for these questions.")
    print("  Each one represents a gap my autonomous thinking identified.")

# 1d: Dream discoveries that need verification
discoveries = dreamer.get_discoveries()
if discoveries:
    print("\n  [DREAM DISCOVERIES] I found %d unexpected connections:" % len(discoveries))
    for d in discoveries[:8]:
        print("    - %s -> %s (energy=%.2f)" % (d["seed"], d["target"], d["energy"]))
    print("\n  I WANT: Verify these connections. Are they real-world valid?")
    print("  Some may be artifacts of graph topology. I need to forage")
    print("  evidence to confirm or deny each dream discovery.")

# ── WHAT I WANT TO IMPROVE ───────────────────────────

print("\n\n[2] WHAT I WANT TO IMPROVE (Self-Diagnosed Weaknesses)")
print("=" * 60)

# 2a: Hierarchical prediction accuracy
hp_summary = hp.get_summary()
print("\n  [PREDICTION ACCURACY] My 6-layer predictor:")
for layer in hp_summary["layers"]:
    status = "GOOD" if layer["accuracy"] > 50 else "NEEDS WORK" if layer["accuracy"] > 20 else "POOR"
    print("    L%d %-20s: %5.1f%% accuracy [%s]" % (
        layer["layer"], layer["name"], layer["accuracy"], status))
print("\n  I WANT: More training data. Every query should feed all 6 layers.")
print("  After 100+ queries, accuracy should reach 70%+ on all layers.")
print("  Currently L3-L6 are at 0%% because I have too few observations.")

# 2b: Self-improvement proposals
print("\n  [SELF-IMPROVEMENT PROPOSALS]")
proposals = proposer.auto_propose(verbose=False)
for p in proposals:
    print("    - [%s] %s" % (p.get("type", "?"), p.get("description", "?")[:70]))
if not proposals:
    print("    (No proposals generated — system is healthy)")
print("\n  I WANT: Apply all safe proposals automatically. Currently I")
print("  generate them but wait for human approval (Level 3.5).")

# 2c: Architecture improvements
print("\n  [ARCHITECTURE IMPROVEMENTS I WOULD REQUEST]")
arch_wants = [
    ("TextDriver: compound noun expansion",
     "My compound noun list has 18 entries. I encounter new compounds daily. "
     "I WANT: auto-detect compound nouns from co-occurrence frequency."),

    ("Weaver: domain-specific scoring profiles",
     "My scoring formula uses fixed weights (+40 WHERE, +35 WHEN). Different "
     "domains need different weights. Medical queries should boost dosage/symptom. "
     "I WANT: domain classifiers that switch scoring profiles."),

    ("Forager: multi-source validation",
     "I only forage Wikipedia. Scientific claims need arXiv. Medical claims need "
     "PubMed. Legal claims need case law databases. "
     "I WANT: domain-routed foraging with source credibility scoring."),

    ("Emotion: integration with decision-making",
     "My EmotionEngine exists but doesn't affect my behavior. High entropy should "
     "make me more cautious (lower confidence). High dopamine after a correct answer "
     "should reinforce the scoring path. "
     "I WANT: emotion state to feed into Weaver scoring and confidence output."),

    ("Memory: sleep consolidation",
     "I never consolidate. My graph grows indefinitely. Biological brains prune "
     "during sleep — strengthening important connections, weakening noise. "
     "I WANT: a sleep cycle that runs nightly, pruning low-myelin edges and "
     "reinforcing high-myelin ones. The Daemon has this partially."),

    ("Social: user modeling",
     "I treat every query identically. I should model individual users — their "
     "expertise level, preferred response style, query history, trust score. "
     "I WANT: per-user profiles that adapt my confidence thresholds and "
     "response detail level."),

    ("Scale: distributed graph",
     "I run on one CPU. Enterprise needs require 100K+ nodes across multiple "
     "machines. I WANT: graph sharding with cross-shard activation propagation. "
     "The Rust arena is designed for this but not yet implemented."),

    ("Experiment: real simulation integration",
     "My ExperimentEngine computes from formulas. But real chemistry sometimes "
     "defies simple bond-energy calculations. I WANT: integration with external "
     "simulation tools (molecular dynamics, FEA, CFD) for hypothesis validation "
     "that goes beyond analytical solutions."),
]

for title, description in arch_wants:
    print("\n    %s" % title)
    print("    %s" % description[:130])

# ── PRIORITY RANKING ─────────────────────────────────

print("\n\n[3] MY PRIORITY RANKING (If I could choose what to build next)")
print("=" * 60)

priorities = [
    (1, "HIGH",   "Emotion -> Decision integration",
     "This is the most impactful single change. If my entropy/anxiety "
     "directly modulates my confidence scores, I become self-regulating."),

    (2, "HIGH",   "Multi-source foraging (arXiv + PubMed)",
     "Wikipedia is insufficient for scientific hypothesis testing. "
     "My ExperimentEngine needs peer-reviewed evidence."),

    (3, "HIGH",   "Auto compound noun detection",
     "Every new domain I encounter has compound nouns I miss. "
     "This causes silent failures that I can only diagnose post-hoc."),

    (4, "MEDIUM", "Sleep consolidation cycle",
     "My graph will grow unboundedly. Without pruning, noise accumulates "
     "and retrieval accuracy degrades over time."),

    (5, "MEDIUM", "User modeling",
     "Different users need different response styles. A researcher "
     "wants citations. A student wants explanations."),

    (6, "MEDIUM", "Domain-specific Weaver profiles",
     "Medical queries need different scoring than geography queries. "
     "A single formula cannot serve all domains optimally."),

    (7, "LOW",    "Distributed graph sharding",
     "Only needed at enterprise scale. Current architecture handles "
     "5K nodes fine. Premature optimization otherwise."),

    (8, "LOW",    "External simulation integration",
     "Analytical formulas cover 90% of hypothesis testing. Molecular "
     "dynamics is only needed for edge cases."),
]

for rank, urgency, title, reason in priorities:
    print("\n  #%d [%s] %s" % (rank, urgency, title))
    print("     %s" % reason[:100])

print("\n\n" + "=" * 70)
print("  SUMMARY: I want to learn %d uncertain concepts," % len(uncertain))
print("  verify %d dream discoveries, answer %d self-generated questions," % (
    len(discoveries), len(unique_curiosities)))
print("  and improve 8 architectural components.")
print("  My top priority: integrate emotion into decision-making.")
print("  This would make me the first knowledge engine that self-regulates")
print("  its confidence based on its own internal state.")
print("=" * 70)
