"""
KOS V8.0 -- Output Validator (LLM Hallucination Guard)

Intercepts LLM-formatted output and validates it against the
original JSON fact contract. Rejects responses that hallucinate
numbers, dates, or proper nouns not in the source facts.

Pipeline:
    facts -> LLM -> validator -> (pass | reject -> raw fallback)
"""

import re


class OutputValidator:
    """Validate LLM output against the source fact contract."""

    def validate(self, llm_output: str, contract: dict) -> dict:
        """
        Check if the LLM output is faithful to the contract.

        Args:
            llm_output: The text generated by the LLM
            contract: The JSON contract sent to the LLM (has 'facts' array)

        Returns:
            {
                "valid": bool,
                "output": str,              # The output to use
                "violations": [str],        # List of violations found
                "used_fallback": bool,      # True if raw evidence was used instead
            }
        """
        facts = contract.get("facts", [])
        facts_text = " ".join(facts).lower()

        violations = []

        # Check 1: Numbers in output must appear in facts
        output_numbers = self._extract_numbers(llm_output)
        fact_numbers = self._extract_numbers(" ".join(facts))
        for num in output_numbers:
            if num not in fact_numbers:
                violations.append(f"Hallucinated number: {num}")

        # Check 2: Dates in output must appear in facts
        output_dates = self._extract_dates(llm_output)
        fact_dates = self._extract_dates(" ".join(facts))
        for date in output_dates:
            if date not in fact_dates:
                violations.append(f"Hallucinated date: {date}")

        # Check 3: Proper nouns in output must appear in facts
        output_nouns = self._extract_proper_nouns(llm_output)
        for noun in output_nouns:
            if noun.lower() not in facts_text:
                violations.append(f"Hallucinated proper noun: {noun}")

        # Check 4: Output should not be empty or trivially short
        if len(llm_output.strip()) < 10:
            violations.append("Output too short")

        if violations:
            # Reject LLM output, fall back to raw evidence
            fallback = "\n".join(facts)
            return {
                "valid": False,
                "output": fallback,
                "violations": violations,
                "used_fallback": True,
            }

        return {
            "valid": True,
            "output": llm_output,
            "violations": [],
            "used_fallback": False,
        }

    def _extract_numbers(self, text: str) -> set:
        """Extract all numbers from text."""
        # Match integers, decimals, percentages, currency
        nums = re.findall(r'\b\d[\d,]*\.?\d*%?\b', text)
        # Normalize: remove commas
        return set(n.replace(",", "") for n in nums)

    def _extract_dates(self, text: str) -> set:
        """Extract date-like patterns."""
        dates = set()
        # Year patterns: 1900-2099
        dates.update(re.findall(r'\b(?:19|20)\d{2}\b', text))
        # Month-year: "January 2024", "Jan 2024"
        dates.update(re.findall(
            r'\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|'
            r'May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|'
            r'Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+\d{4}\b',
            text, re.I))
        return dates

    def _extract_proper_nouns(self, text: str) -> set:
        """Extract capitalized proper nouns (simple heuristic)."""
        # Skip sentence starts by looking for mid-sentence capitals
        words = text.split()
        nouns = set()
        for i, word in enumerate(words):
            # Skip first word of sentences
            if i > 0 and words[i-1][-1] not in '.!?':
                clean = re.sub(r'[^\w]', '', word)
                if clean and clean[0].isupper() and len(clean) > 1:
                    nouns.add(clean)
        return nouns
